services:
  # Loki - система сбора и индексации логов
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-configs.yaml:/etc/loki/configs.yaml
      - loki_data:/loki
    command: -configs.file=/etc/loki/local-configs.yaml
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3100/ready" ]
      interval: 10s
      retries: 5
      start_period: 5s

  # Promtail - агент для пересылки логов в Loki
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-configs.yaml:/etc/promtail/configs.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -configs.file=/etc/promtail/configs.yaml
    depends_on:
      - loki

volumes:
  loki_data:
