limits_config:
  retention_period: 7d  # Хранить логи 7 дней

schema_config:
  configs:
    - from: 2020-07-01  # с какой даты начинается применение данной конфигурации.
      store: boltdb-shipper # Это указывает на тип хранилища индекса логов.
      object_store: filesystem # куда будут сохраняться сами логи (не индексы, а фактические данные).
      schema: v11 #Э то версия схемы данных, используемой для хранения индексов.
      index: # Настройки индексации логов.
        prefix: index_ # Префикс для имен файлов индексов. Все индексы будут начинаться с
        period: 24h # Период времени, за который создается один индекс.