# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Правила алертинга
rule_files:
  - "alerts_rules.yml"

# Конфигурация алертменеджера
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Мониторинг сервиса авторизации
  - job_name: 'auth_service'
    metrics_path: '/metrics'
    scrape_interval: 15s  # Более частый опрос для сервиса авторизации
    static_configs:
      - targets: ['auth-app:8080']

    # Добавляем метки для сервиса
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: []
        target_label: service
        replacement: 'auth-service'

  # Redis Exporter для мониторинга Redis
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

    # Добавляем метки для Redis
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: []
        target_label: service
        replacement: 'redis'

  # PostgreSQL Exporter для мониторинга PostgreSQL
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

    # Добавляем метки для PostgreSQL
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: []
        target_label: service
        replacement: 'postgres'

  # Мониторинг хоста с помощью Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: [ '194.87.95.28:9100:9100' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'host-system'
