# prometheus.yml для отправки метрик в Grafana Cloud
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Настройка удаленной записи в Grafana Cloud
remote_write:
  - url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
    basic_auth:
      username: 2335073
      password: glc_eyJvIjoiMTM4MTQ0MyIsIm4iOiJwZGMtdGVhbWVtYWlscHJhYy1kZWZhdWx0LWF1dGhzZXJ2aWNlIiwiayI6IllBOWc3NkZTMTRqQjdydUpNMTdaZEE5MSIsIm0iOnsiciI6InByb2QtdXMtd2VzdC0wIn19

# Правила алертинга
rule_files:
  - "alerts_rules.yml"


scrape_configs:
  # Мониторинг внешнего сервера
  - job_name: 'external_server'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['194.87.95.28:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: []
        target_label: service
        replacement: 'external-server'

  # Мониторинг сервиса авторизации
  - job_name: 'auth_service'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['auth-app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: []
        target_label: service
        replacement: 'auth-service'

  # Redis Exporter для мониторинга Redis
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: []
        target_label: service
        replacement: 'redis'

  # PostgreSQL Exporter для мониторинга PostgreSQL
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: []
        target_label: service
        replacement: 'postgres'
