{
 "title": "Auth Service",
 "tags": [
  "auth-service",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Источник данных", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Метрики PUT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Среднее время ответа",
   "type": "gauge",
   "description": "Вычисляет среднее время ответа, разделяя сумму всех времен на количество запросов за 5-минутный период.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_time_seconds_sum{method=\"PUT\"}[5m])) / sum(rate(auth_service_http_response_time_seconds_count{method=\"PUT\"}[5m]))\n\n",
     "legendFormat": "{{path}} - P95"
    }
   ]
  },
  {
   "title": "Количество ошибок (4xx и 5xx)",
   "type": "gauge",
   "description": " Показывает частоту ошибок клиента (4xx) и сервера (5xx) за скользящее 5-минутное окно. Этот показатель особенно важен для мониторинга проблем.",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{method=\"PUT\", code=~\"[45]..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95-й процентиль времени ответа",
   "type": "gauge",
   "description": "Показывает порог, ниже которого находятся 95% всех запросов. Важный показатель производительности, более устойчивый к выбросам чем среднее значение.",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(auth_service_http_response_time_seconds_bucket{method=\"PUT\"}[5m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "stat",
   "description": "Показывает среднюю частоту запросов за последние 5 минут. Запрос rate() берет общее изменение счетчика за 5-минутное окно и делит на 300 секунд для получения значения в секунду.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{method=\"PUT\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Метрики POST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Среднее время ответа",
   "type": "gauge",
   "description": "Вычисляет среднее время ответа, разделяя сумму всех времен на количество запросов за 5-минутный период.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_time_seconds_sum{method=\"POST\"}[5m])) / sum(rate(auth_service_http_response_time_seconds_count{method=\"POST\"}[5m]))\n\n",
     "legendFormat": "{{path}} - P95"
    }
   ]
  },
  {
   "title": "Количество ошибок (4xx и 5xx)",
   "type": "gauge",
   "description": " Показывает частоту ошибок клиента (4xx) и сервера (5xx) за скользящее 5-минутное окно. Этот показатель особенно важен для мониторинга проблем.",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{method=\"POST\", code=~\"[45]..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95-й процентиль времени ответа",
   "type": "gauge",
   "description": "Показывает порог, ниже которого находятся 95% всех запросов. Важный показатель производительности, более устойчивый к выбросам чем среднее значение.",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(auth_service_http_response_time_seconds_bucket{method=\"POST\"}[5m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "stat",
   "description": "Показывает среднюю частоту запросов за последние 5 минут. Запрос rate() берет общее изменение счетчика за 5-минутное окно и делит на 300 секунд для получения значения в секунду.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{method=\"POST\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Метрики GET", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Среднее время ответа",
   "type": "gauge",
   "description": "Вычисляет среднее время ответа, разделяя сумму всех времен на количество запросов за 5-минутный период.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_time_seconds_sum{method=\"GET\"}[5m])) / sum(rate(auth_service_http_response_time_seconds_count{method=\"GET\"}[5m]))\n\n",
     "legendFormat": "{{path}} - P95"
    }
   ]
  },
  {
   "title": "Количество ошибок (4xx и 5xx)",
   "type": "gauge",
   "description": " Показывает частоту ошибок клиента (4xx) и сервера (5xx) за скользящее 5-минутное окно. Этот показатель особенно важен для мониторинга проблем.",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{method=\"GET\", code=~\"[45]..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95-й процентиль времени ответа",
   "type": "gauge",
   "description": "Показывает порог, ниже которого находятся 95% всех запросов. Важный показатель производительности, более устойчивый к выбросам чем среднее значение.",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(auth_service_http_response_time_seconds_bucket{method=\"GET\"}[5m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "stat",
   "description": "Показывает среднюю частоту запросов за последние 5 минут. Запрос rate() берет общее изменение счетчика за 5-минутное окно и делит на 300 секунд для получения значения в секунду.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{method=\"GET\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Количество кодов за 5 мин", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "2хх ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx успешные"
    }
   ]
  },
  {
   "title": "5хх",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 4хх",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"4..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Основные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Запросов в секунду по эндпоинтам",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total[1m])) by (method)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Распределение успешных запросов по методам (5 мин",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"2..\"}[5m])) by (method)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Ошибки и алерты", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Ошибки за минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"[45]..\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Процент ошибок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{code=~\"5..\"}[5m])) / sum(rate(auth_service_http_response_codes_total[5m]))",
     "legendFormat": "5xx ошибки"
    },
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{code=~\"4..\"}[5m])) / sum(rate(auth_service_http_response_codes_total[5m]))",
     "legendFormat": "4xx ошибки"
    }
   ]
  }
 ]
}