{
 "title": "Auth Service",
 "tags": [
  "auth-service",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Источник данных", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Количество кодов за 5 мин", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2хх ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx успешные"
    }
   ]
  },
  {
   "title": "5хх",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 4хх",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"4..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Основные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Запросов в секунду по эндпоинтам",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Распределение успешных запросов по методам (5 мин",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"2..\"}[5m])) by (method)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Время ответа по эндпоинтам",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_service_http_response_time_p95_seconds{quantile=\"0.95\"}",
     "legendFormat": "{{path}} - P95"
    }
   ]
  },
  { "title": "Ошибки и алерты", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ошибки за минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(auth_service_http_response_codes_total{code=~\"[45]..\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Процент ошибок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{code=~\"5..\"}[5m])) / sum(rate(auth_service_http_response_codes_total[5m]))",
     "legendFormat": "5xx ошибки"
    },
    {
     "expr": "sum(rate(auth_service_http_response_codes_total{code=~\"4..\"}[5m])) / sum(rate(auth_service_http_response_codes_total[5m]))",
     "legendFormat": "4xx ошибки"
    }
   ]
  }
 ]
}