global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: [ 'auth-service:8080' ]
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'node'
    static_configs:
      - targets: [ 'auth-node-exporter:9100' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'host-system'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: '/metrics'
    scrape_interval: 30s 