name: Deploy Auth CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/Auth"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/Auth
            
            # Create .env file
            echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
            chmod 600 .env
            
            # Проверяем существование файлов docker-compose
            if [ ! -f "docker-compose.yaml" ]; then
              echo "docker-compose.yaml not found!"
              ls -la
              exit 1
            fi
            
            # Используем docker-compose вместо docker compose, если доступен
            if command -v docker-compose &> /dev/null; then
              # Stop all running containers
              docker-compose -f docker-compose.yaml -f docker-compose-loki.yaml down
            
              # Build the containers
              docker-compose -f docker-compose.yaml -f docker-compose-loki.yaml build
            
              # Modify docker-compose.yaml temporarily
              sed -i.bak 's/- "8080:8080"/# - "8080:8080"/' docker-compose.yaml
            
              # Run migrations
              docker-compose -f docker-compose.yaml run --rm auth-app ./auth-app -migrate || true
            
              # Restore the original file
              mv docker-compose.yaml.bak docker-compose.yaml
            
              # Start containers
              docker-compose -f docker-compose.yaml -f docker-compose-loki.yaml up -d
            
              # Check status
              sleep 5
              docker-compose -f docker-compose.yaml -f docker-compose-loki.yaml ps
            else
              # Попытаемся использовать docker compose (новый синтаксис)
              # Stop all running containers
              docker compose -f docker-compose.yaml -f docker-compose-loki.yaml down
            
              # Build the containers
              docker compose -f docker-compose.yaml -f docker-compose-loki.yaml build
            
              # Modify docker-compose.yaml temporarily
              sed -i.bak 's/- "8080:8080"/# - "8080:8080"/' docker-compose.yaml
            
              # Run migrations
              docker compose -f docker-compose.yaml run --rm auth-app ./auth-app -migrate || true
            
              # Restore the original file
              mv docker-compose.yaml.bak docker-compose.yaml
            
              # Start containers
              docker compose -f docker-compose.yaml -f docker-compose-loki.yaml up -d
            
              # Check status
              sleep 5
              docker compose -f docker-compose.yaml -f docker-compose-loki.yaml ps
            fi