name: Deploy Auth CI/CD

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/auth-deploy"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/auth-deploy
            
            # Create .env file
            echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
            chmod 600 .env
            
            # Stop all running containers
            docker compose down
            
            # Build the containers
            docker compose build
            
            # Modify docker-compose.yaml temporarily to remove port binding during migration
            sed -i.bak 's/- "8080:8080"/# - "8080:8080"/' docker-compose.yaml
            
            # Run a separate container only for migrations
            docker compose run --rm auth-app ./auth-app -migrate || true
            
            # Restore the original docker-compose file
            mv docker-compose.yaml.bak docker-compose.yaml
            
            # Start all containers normally
            docker compose up -d
            
            # Check the status
            sleep 5
            docker compose ps
            
            # Restart systemd service if needed
            sudo systemctl restart auth || true