name: Deploy Auth CI/CD

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # клонирование репозитория (без .env, он в .gitignore)

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/auth-deploy"

      # вот новый шаг, создающий .env на сервере!
      - name: Create .env file on server (automatic from GitHub Secret)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE_CONTENTS }}" > ~/auth-deploy/.env
            chmod 600 ~/auth-deploy/.env

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/auth-deploy
            docker compose down
            docker compose build
            docker compose up -d
            
            # исправленная миграция БД с проверкой схемы
            DSN=$(grep DATABASE_DSN .env | cut -d '=' -f2-)
            if [[ $DSN != postgres://* ]]; then
              # Если нет схемы postgres://, добавим её
              DSN="postgres://$DSN"
            fi
            migrate -path ./db/migrations -database "$DSN" up

            # перезапустить systemd сервис, если используется
            sudo systemctl restart auth || true