name: Deploy Auth CI/CD

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # клонирование репозитория (без .env, он в .gitignore)

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/auth-deploy"

      # создание .env на сервере из GitHub Secret
      - name: Create .env file on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE_CONTENTS }}" > ~/auth-deploy/.env
            chmod 600 ~/auth-deploy/.env

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/auth-deploy
            
            # Проверка и освобождение порта 8080 перед запуском
            PORT_PID=$(sudo lsof -t -i:8080 || echo "")
            if [ ! -z "$PORT_PID" ]; then
              echo "Освобождение порта 8080, занятого процессом $PORT_PID"
              sudo kill -9 $PORT_PID || true
              sleep 2
            fi
            
            # Остановка всех контейнеров
            docker compose down
            
            # Сборка новых образов
            docker compose build
            
            # Запуск контейнеров в detached режиме
            docker compose up -d
            
            # Ждем, пока контейнер PostgreSQL полностью запустится и будет готов
            echo "Ожидание готовности PostgreSQL..."
            docker compose exec -T postgres sh -c 'until pg_isready -U admin -d mydb; do sleep 2; done'
            
            # Запуск миграций внутри контейнера auth-app
            echo "Запуск миграций..."
            docker compose exec -T auth-app ./auth-app -migrate
            
            # Проверка статуса контейнеров после применения миграций
            docker compose ps
            
            # Проверка логов auth-app
            docker compose logs --tail 20 auth-app
            
            # перезапустить systemd сервис, если используется
            sudo systemctl restart auth || true