name: Deploy Auth CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/Auth"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 20m
          command_timeout: 15m
          script: |
            cd /home/Auth
            
            # Create .env file
            echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
            chmod 600 .env
            
            # Проверяем существование файлов docker-compose
            if [ ! -f "docker-compose.yaml" ]; then
              echo "docker-compose.yaml not found!"
              ls -la
              exit 1
            fi
            
            # Очистка старых образов для экономии места
            docker image prune -f || true
            
            # Используем docker-compose вместо docker compose, если доступен
            if command -v docker-compose &> /dev/null; then
              # Stop all running containers
              docker-compose down --remove-orphans
              
              # Всегда пересобираем для обновления кода
              echo "Building auth-service..."
              DOCKER_BUILDKIT=1 docker-compose build --no-cache auth-service
              
              # Start containers
              docker-compose up -d
            
              # Check status
              sleep 2
              docker-compose ps
            else
              # Попытаемся использовать docker compose (новый синтаксис)
              # Stop all running containers
              docker compose down --remove-orphans
              
              # Всегда пересобираем для обновления кода
              echo "Building auth-service..."
              DOCKER_BUILDKIT=1 docker compose build --no-cache auth-service
              
              # Start containers
              docker compose up -d
            
              # Check status
              sleep 2
              docker compose ps
            fi