name: Deploy Auth CI/CD

on:
  push:
    branches: [ "mainReadyTrade", "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/Auth
            
            # Update code
            git pull origin main
            
            # Create .env file
            echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
            chmod 644 .env
            
            # Quick restart with cache
            docker-compose down
            docker-compose up -d --build
            
            # Run migrations
            docker-compose exec -T auth-service ./auth-app -migrate || true
            
            # Check status
            sleep 3
            docker-compose ps